services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file: .env
    restart: unless-stopped
    container_name: ramsey

  redis:
    image: redis:6.2-alpine
    ports:
      - "6378:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    container_name: ramsey-redis

volumes:
  cache:
    driver: local
